kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane # Node do Control-Plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
- role: worker # Node onde vai rodar os pods
- role: worker
containerdConfigPatches: # Usando para registry privados
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."harbor.localhost.com"]
      endpoint = ["https://harbor.localhost.com"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."harbor.localhost.com".tls]
        insecure_skip_verify = true